license="All rights reserved"

modLoader="javafml"

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

[[mods]] #mandatory

modId="workers"

version="1.7.2"

displayName="Workers Mod"
updateJSONURL="https://raw.githubusercontent.com/talhanation/workers/main/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/workers"

logoFile="logo.png"

credits="talhanation"

authors="talhanation"
# The description text for the mod (multi line!) (#mandatory)
description='''
This Mod adds hireable Villager Workers into Minecraft.
'''